### ISSUE TITLE
The size of tensor a (64) must match the size of tensor b (16) at non-singleton dimension 0

### ISSUE THREAD

**Issue by LTranData** [Jaychoukobbe/GaitPart#6]
I got this error while training
```bash
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/home/asilla/10_dataset/lamtt/GaitPart/model/model.py", line 175, in fit
    feature, label_prob = self.encoder(*seq, batch_frame)
  File "/home/asilla/miniconda3/envs/lam-py36-torch15/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asilla/miniconda3/envs/lam-py36-torch15/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/asilla/miniconda3/envs/lam-py36-torch15/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/asilla/miniconda3/envs/lam-py36-torch15/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/asilla/miniconda3/envs/lam-py36-torch15/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/asilla/miniconda3/envs/lam-py36-torch15/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/asilla/miniconda3/envs/lam-py36-torch15/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asilla/10_dataset/lamtt/GaitPart/model/network/gaitpart.py", line 100, in forward
    feature = feature.matmul(self.fc_bin)
RuntimeError: The size of tensor a (64) must match the size of tensor b (16) at non-singleton dimension 0
```

Can anyone tell me how to fix it?

**Comment by OliverHxh** [comment]
Already fixed，you can pull the latest version.
